// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MyFood.EditorApp.ApiClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class RecipeDescriptionDto
    {
        /// <summary>
        /// Initializes a new instance of the RecipeDescriptionDto class.
        /// </summary>
        public RecipeDescriptionDto() { }

        /// <summary>
        /// Initializes a new instance of the RecipeDescriptionDto class.
        /// </summary>
        public RecipeDescriptionDto(Guid? id = default(Guid?), string title = default(string), string previewUrl = default(string), string complexity = default(string), string duration = default(string))
        {
            Id = id;
            Title = title;
            PreviewUrl = previewUrl;
            Complexity = complexity;
            Duration = duration;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "previewUrl")]
        public string PreviewUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "complexity")]
        public string Complexity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "duration")]
        public string Duration { get; set; }

    }
}
