// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MyFood.EditorApp.Api.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class RecipeDto
    {
        /// <summary>
        /// Initializes a new instance of the RecipeDto class.
        /// </summary>
        public RecipeDto() { }

        /// <summary>
        /// Initializes a new instance of the RecipeDto class.
        /// </summary>
        public RecipeDto(string title = default(string), string previewUrl = default(string), string description = default(string), string complexity = default(string), string duration = default(string), IList<string> ingredients = default(IList<string>), IList<StepDto> steps = default(IList<StepDto>), IList<string> devices = default(IList<string>))
        {
            Title = title;
            PreviewUrl = previewUrl;
            Description = description;
            Complexity = complexity;
            Duration = duration;
            Ingredients = ingredients;
            Steps = steps;
            Devices = devices;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "previewUrl")]
        public string PreviewUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "complexity")]
        public string Complexity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "duration")]
        public string Duration { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ingredients")]
        public IList<string> Ingredients { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "steps")]
        public IList<StepDto> Steps { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "devices")]
        public IList<string> Devices { get; set; }

    }
}
